# Generated by Django 5.2.17 on 2026-09-23 16:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('initial_budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('contractors', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(default='Lakhs', max_length=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=120)),
                ('vendor', models.CharField(max_length=120)),
                ('total', models.CharField(max_length=40)),
                ('advance_paid', models.CharField(max_length=40)),
                ('balance_due', models.CharField(max_length=40)),
                ('due_date', models.CharField(max_length=60)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='ledger.project')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=80)),
                ('material_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('labor_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(default='In Progress', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='ledger.project')),
            ],
        ),
    ]
